---
- name: copy php config files
  tags: php74-config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ install_configs }}"
  notify:
    - restart php74-php-fpm
  when:
    - install_configs is defined
    - install_configs | length != 0
