---
- name: install dependency packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - policycoreutils-python
    - openssh-server

- name: copy gitlab-ce repo
  copy:
    src: gitlab-ce.repo
    dest: /etc/yum.repos.d/gitlab-ce.repo
    owner: root
    group: root
    mode: 0644

- name: install gitlab-ce
  package:
    name: gitlab-ce
    state: present

- name: enable gitlab service
  service:
    name: gitlab-runsvdir
    state: started
    enabled: yes
