---
- name: set sudoers for redhat os family
  lineinfile:
    path: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel   ALL=(ALL)   NOPASSWD: ALL"
  when:
    - ansible_facts.os_family.lower() == 'redhat'

- name: set sudoers for debian os family
  lineinfile:
    path: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo   ALL=(ALL:ALL)   NOPASSWD: ALL"
  when:
    - ansible_facts.os_family.lower() == 'debian'
