---
- name: reload php72-php-fpm
  tags: php72-service, php72-service-reload, php72-service-start
  service:
    name: php72-php-fpm
    state: reloaded
    enabled: yes
  when:
    - start_php72_service is defined
    - start_php72_service | bool

- name: stopped and disable php72-php-fpm
  tags: php72-service, php72-service-disable, php72-service-stop
  service:
    name: php72-php-fpm
    state: stopped
    enabled: no
  when:
    - start_php72_service is defined
    - not (start_php72_service | bool)
