---
- name: copy php config files
  tags: php72-config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ install_configs }}"
  notify:
    - reload php72-php-fpm

- name: copy php config files of user custom
  tags: php72-config, php72-config-custom
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ custom_install_configs }}"
  notify:
    - reload php72-php-fpm