- name: copy mariadb repository
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root
    group: root
    mode: "0644"

- name: install mariadb server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - MariaDB-server
    - MariaDB-client
