---
- name: install dependency packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - mariadb-libs

- name: modify bind-address
  lineinfile:
    path: /etc/my.cnf
    regexp: "^bind-address="
    line: bind-address={{ mariadb_bind_address }}
    insertafter: "^\\[mysqld\\]"
  notify:
    - restart mariadb

- name: ensure mariadb is running
  service:
    name: mariadb
    state: started
    enabled: yes