---
all:
  hosts:
    10.0.100.[9:18]:
      ansible_user: root
  children:
    salt_master:
      hosts:
        10.0.100.[11:12]:
    ha:
      hosts:
        10.0.100.[9:10]:
    ceph:
      hosts:
        10.0.100.[11:18]:
