---
- hosts: all
  gather_facts: true
  roles:
    - role: authorized_key
      vars:
        users:
          - name: root
            state: present
            key: "http://10.0.100.1/keys/zhanghe.pub"
    - role: system-init
      tags: system-init
    - role: sudoers
      tags: sudo
    - role: ntpd
      tags: ntpd
