---
- hosts: all
  roles:
    - role: sudoers
      tags: sudoers
    - role: system-init
      tags: system-init
    - role: authorized_key
      tags: authorized_key
      vars:
        users:
        - name: root
          state: present
          key: root.pub
    - role: resolv
      tags: rosolv
      vars:
        resolv_search:
          - "fdisk.cc"
        resolv_domain: "fdisk.cc"
        resolv_nameservers:
          - "223.5.5.5"
          - "223.6.6.6"
    - role: ntp
      tags: ntp
      vars:
        ntp_servers:
          - ntp.aliyun.com
        ntp_restricts:
          - network: 10.0.100.0
            netmask: 255.255.0.0
    - role: dirs
      tags: dirs
      vars:
        dirs:
          - path: /data/html
          - path: /data/cap
          - path: /data/logs

- hosts: 10.0.100.1
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: vm01.fdisk.cc
    - role: cobbler
      tags: cobbler
      vars:
        cobbler_domain_name: "fdisk.cc"
        cobbler_domain_name_servers: "10.0.100.1"
        cobbler_dhcp_range: "10.0.100.98 10.0.100.99"
        dobbler_dhcp_network: "10.0.100.0"
        cobbler_dhcp_netmask: "255.255.255.0"
        cobbler_dhcp_gateway: "10.100.0.254"
        cobbler_default_password: "$1$ta0cyI2Z$CHpEuSN.Nm60y2eXMrAaj."
    #- role: capistrano
    #  tags: capistrano
    - role: jenkins
      tags: jenkins
    - role: nodejs
      tags: nodejs
    - role: rabbitmq
      tags: rabbitmq

- hosts: 10.0.100.3
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: master01.fdisk.cc
    - role: etcd
      tags: etcd
      vars:
        etcd_name: "infra01"
        etcd_enable_v2: yes
        etcd_data_dir: "/data/etcd"
        etcd_listen_client_urls: "https://10.0.100.3:2379"
        etcd_listen_peer_urls: "https://10.0.100.3:2380"
        etcd_advertise_client_urls: "https://10.0.100.3:2379"
        etcd_initial_advertise_peer_urls: "https://10.0.100.3:2380"
        etcd_initial_cluster_token: "infra-cluster"
        etcd_initial_cluster: "infra01=https://10.0.100.3:2380,infra02=https://10.0.100.4:2380,infra03=https://10.0.100.5:2380"
        etcd_tls: yes
        etcd_cert_file: "etcd.pem"
        etcd_key_file: "etcd-key.pem"
        etcd_client_cert_auth: yes
        etcd_trusted_ca_file: "ca.pem"
        etcd_auto_tls: no
        etcd_peer_cert_file: "etcd.pem"
        etcd_peer_key_file: "etcd-key.pem"
        etcd_peer_client_cert_auth: yes
        etcd_peer_trusted_ca_file: "ca.pem"
        etcd_peer_auto_tls: no
        etcd_listen_metrics_urls: "http://10.0.100.3:2381"

- hosts: 10.0.100.4
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: master02.fdisk.cc
    - role: etcd
      tags: etcd
      vars:
        etcd_name: "infra02"
        etcd_enable_v2: yes
        etcd_data_dir: "/data/etcd"
        etcd_listen_client_urls: "https://10.0.100.4:2379"
        etcd_listen_peer_urls: "https://10.0.100.4:2380"
        etcd_advertise_client_urls: "https://10.0.100.4:2379"
        etcd_initial_advertise_peer_urls: "https://10.0.100.4:2380"
        etcd_initial_cluster_token: "infra-cluster"
        etcd_initial_cluster: "infra01=https://10.0.100.3:2380,infra02=https://10.0.100.4:2380,infra03=https://10.0.100.5:2380"
        etcd_tls: yes
        etcd_cert_file: "etcd.pem"
        etcd_key_file: "etcd-key.pem"
        etcd_client_cert_auth: yes
        etcd_trusted_ca_file: "ca.pem"
        etcd_auto_tls: no
        etcd_peer_cert_file: "etcd.pem"
        etcd_peer_key_file: "etcd-key.pem"
        etcd_peer_client_cert_auth: yes
        etcd_peer_trusted_ca_file: "ca.pem"
        etcd_peer_auto_tls: no
        etcd_listen_metrics_urls: "http://10.0.100.4:2381"

- hosts: 10.0.100.5
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: master03.fdisk.cc
    - role: etcd
      tags: etcd
      vars:
        etcd_name: "infra03"
        etcd_enable_v2: yes
        etcd_data_dir: "/data/etcd"
        etcd_listen_client_urls: "https://10.0.100.5:2379"
        etcd_listen_peer_urls: "https://10.0.100.5:2380"
        etcd_advertise_client_urls: "https://10.0.100.5:2379"
        etcd_initial_advertise_peer_urls: "https://10.0.100.5:2380"
        etcd_initial_cluster_token: "infra-cluster"
        etcd_initial_cluster: "infra01=https://10.0.100.3:2380,infra02=https://10.0.100.4:2380,infra03=https://10.0.100.5:2380"
        etcd_tls: yes
        etcd_cert_file: "etcd.pem"
        etcd_key_file: "etcd-key.pem"
        etcd_client_cert_auth: yes
        etcd_trusted_ca_file: "ca.pem"
        etcd_auto_tls: no
        etcd_peer_cert_file: "etcd.pem"
        etcd_peer_key_file: "etcd-key.pem"
        etcd_peer_client_cert_auth: yes
        etcd_peer_trusted_ca_file: "ca.pem"
        etcd_peer_auto_tls: no
        etcd_listen_metrics_urls: "http://10.0.100.5:2381"

- hosts: 10.0.100.6
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: node01.fdisk.cc
    - role: docker-ce
      tags: docker

- hosts: 10.0.100.7
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: node02.fdisk.cc

- hosts: 10.0.100.8
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: node03.fdisk.cc
