---
- hosts: all
  roles:
    - role: sudoers
    - role: system-init
    #- role: authorized_key
    #  vars:
    #    users:
    #    - name: zhanghe
    #      state: present
    #      key: zhanghe.pub
