---
- hosts: all
  roles:
    - role: system-init
      tags: system-init

    - role: ntpd
      tags: ntpd

    - role: sudoers
      tags: sudo, sudoers

    - role: authorized_key
      tags: nopass, authorized_key
      vars:
        users:
          - name: root
            state: present
            key: root.pub

    - role: resolv
      tags: resolv
      vars:
        resolv_search:
          - "fdisk.cc"
        resolv_domain: "fdisk.cc"
        resolv_nameservers:
          - "10.0.0.254"

    - role: docker-ce
      tags: docker
      vars:
        docker_daemon_force: yes
        docker_compose: yes

- hosts: 10.0.100.2
  roles:
    - role: php72
      tags: php72
      vars:
        start_php72_service: yes

    - role: nfs
      tags: nfs-server
