---
- hosts: all
  roles:
    - role: system-init
      tags: system-init
    - role: ntpd
      tags: ntpd
    # - role: sudoers
    #   tags: sudoers
    # - role: authorized_key
    #   tags: authorized_key
    #   vars:
    #     users:
    #       - name: root
    #         state: present
    #         key: root.pub
    - role: resolv
      tags: resolv
      vars:
        resolv_search:
          - "fdisk.cc"
        resolv_domain: "fdisk.cc"
        resolv_nameservers:
          - "10.0.0.254"
          - "223.5.5.5"
          - "223.6.6.6"
          - "223.7.7.7"

- hosts: 10.0.100.1
  roles:
    - role: hostname
      tags: hostname
      vars:
        hostname: "vm01.fdisk.cc"
