---
- hosts: all
  roles:
    # - role: sudoers
    #   tags: sudoers
    # - role: system-init
    #   tags: system-init
    # - role: authorized_key
    #   tags: authorized_key
    #   vars:
    #     users:
    #       - name: root
    #         state: present
    #         key: root.pub
    # - role: resolv
    #   tags: rosolv
    #   vars:
    #     resolv_search:
    #       - "fdisk.cc"
    #     resolv_domain: "fdisk.cc"
    #     resolv_nameservers:
    #       - "10.0.100.11"
    - role: ntpd
      tags: ntpd
      # vars:
      #  ntp_servers:
      #    - ntp.aliyun.com
      #  ntp_restricts:
      #    - network: 10.0.100.0
      #      netmask: 255.255.0.0
