---
- hosts: all
  gather_facts: true
  roles:
    - role: authorized_key
      vars:
        users:
          - name: root
            state: present
            key: "http://10.0.100.1/keys/zhanghe.pub"
    - role: system-init
      tags: system-init
    - role: sudoers
      tags: sudo
    - role: ntpd
      tags: ntpd
    - role: saltstack
      tags: saltstack, salt_minion
      vars:
        salt_role: minion

- hosts: salt_master
  roles:
    - role: saltstack
      tags: saltstack, salt_master
      vars:
        salt_role: master
        autosign_hosts:
          - "*.fdisk.cc"
