---
disable_password_authentication: no
disable_swap: yes

packages:
  - vim
  - gcc
  - gcc-c++
  - net-tools
  - htop
  - iftop
  - ack
  - nmap-ncat
  - wget
  - python3

limits:
  - "*  soft  nofile  819200"
  - "*  hard  nofile  819200"
  - "*  soft  nproc   819200"
  - "*  hard  nproc   819200"

tzname: Asia/Shanghai

disable_services:
  - postfix
  - kdump
  - NetworkManager

disable_services_rhel6:
  - iptables

disable_services_rhel7:
  - firewalld

sysctl_config:
  - { name: "net.core.somaxconn", value: "65535" }
  - { name: "net.ipv4.tcp_max_syn_backlog", value: "262144" }
  - { name: "net.ipv4.tcp_syncookies", value: "1" }
  - { name: "net.ipv4.tcp_max_tw_buckets", value: "262144" }
  - { name: "net.core.netdev_max_backlog", value: "262144" }
  - { name: "net.ipv4.ip_local_port_range", value: "1024 65000" }
  - { name: "net.ipv4.tcp_tw_reuse", value: "1" }
  - { name: "net.ipv4.tcp_tw_recycle", value: "0" }
  - { name: "net.ipv4.tcp_timestamps", value: "0" }
  - { name: "net.ipv4.tcp_synack_retries", value: "2" }
  - { name: "net.ipv4.tcp_fin_timeout", value: "1" }
  - { name: "net.ipv4.tcp_keepalive_time", value: "30" }
