---
- name: install epel-release
  package:
    name: epel-release
    state: present

- name: install the related pakcage for cobbler
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - syslinux
    - dhcp
    - tftp-server
    - pykickstart
    - cobbler
    - cobbler-web
  notify:
    - restart httpd
    - restart cobblerd
    - restart tftp
    - restart rsyncd

- name: flush handlers
  meta: flush_handlers

- name: copy file to /etc/cobbler/
  copy:
    src: "{{ item }}"
    dest: /etc/cobbler/{{ item }}
    owner: root
    group: root
    mode: 0644
  notify:
    - restart cobblerd
    - cobbler sync
  with_items:
    - modules.conf

- name: render template for /etc/cobbler/dhcp.template
  template:
    src: dhcp.template.j2
    dest: /etc/cobbler/dhcp.template
    owner: root
    group: root
    mode: 0644
  notify:
    - restart cobblerd
    - cobbler sync

- name: change the cobbler server address
  lineinfile:
    path: /etc/cobbler/settings
    regexp: "^server:"
    line: "server: {{ ansible_default_ipv4.address }}"
  notify:
    - restart cobblerd
    - cobbler sync

- name: change the cobbler next_server address
  lineinfile:
    path: /etc/cobbler/settings
    regexp: "^next_server:"
    line: "next_server: {{ ansible_default_ipv4.address }}"
  notify:
    - restart cobblerd

- name: change the cobbler manage services
  lineinfile:
    path: /etc/cobbler/settings
    regexp: "^manage_{{ item }}:"
    line: "manage_{{ item }}: 1"
  notify:
    - restart cobblerd
    - cobbler sync
  with_items:
    - rsync
    - dhcp
    - tftpd

- name: cobbler get-loaders
  shell: cobbler get-loaders
  args:
    creates: /var/lib/cobbler/loaders/pxelinux.0
  notify:
    - restart cobblerd
    - cobbler sync

- name: set default password
  lineinfile:
    path: /etc/cobbler/settings
    regexp: "^default_password_crypted"
    line: "default_password_crypted: {{ default_password }}"
  notify:
    - restart cobblerd
    - cobbler sync

- name: copy kickstarts to destination
  copy:
    src: "{{ item }}"
    dest: /var/lib/cobbler/kickstarts
    owner: root
    group: root
    mode: 0644
  notify:
    - cobbler sync
  with_items:
    - CentOS7.ks

- name: ensure service is running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - httpd
    - cobblerd
    - tftp
    - rsyncd