---
- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted
    enabled: yes

- name: restart dhcrelay
  systemd:
    name: dhcrelay
    daemon_reload: yes
    state: restarted
    enabled: yes