---
- name: install nodejs for rhel 7 family
  block:
    - name: create nodejs logs directory (/data/logs/nodejs)
      import_role:
        name: dirs
      vars:
        dirs:
          - path: /data/logs/nodejs
            owner: www
            group: www
            mode: '0755'
            recurse: yes

    - name: create pm2 logrotate scripts directory (/opt/scripts)
      import_role:
        name: dirs
      vars:
        dirs:
          - path: /opt/scripts
            owner: root
            group: root
            mode: '0755'

    - name: install nodejs 10.x
      tags: nodejs-install
      import_tasks: nodejs_install.yaml

    - name: config pm2 logrotate
      tags: nodejs-logroate, pm2-logrotate
      import_tasks: nodejs_logrotate.yaml
      when:
        - pm2_logrotate_enable is defined
        - pm2_logrotate_enable | bool

  when:
    - ansible_facts.os_family.lower() == 'redhat'
    - ansible_facts.distribution_major_version == '7'