---
- name: install and config nfs server
  block:
    - name: install nfs
      tags: nfs_install
      import_tasks: nfs_server.yaml
  when:
    - ansible_facts.os_family.lower() == 'redhat'
    - ansible_facts.distribution_major_version == '7'