---
- name: install nfs server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rpcbind
    - nfs-utils

- name: config nfs server exports
  block:
    - name: create shared directory
      file:
        path: "{{ item.shared_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0777'
      with_items: "{{ nfs_exports }}"

    - name: render nfs exports config
      template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart nfs
  when:
    - nfs_exports is defined
    - nfs_exports | length != 0
    - nfs_server | bool

- name: config nfs client mounts
  mount:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    state: "{{ item.state | default('present') }}"
    fstype: 'nfs'
    opts: "{{ item.opts | default('_netdev,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2') }}"
  with_items: "{{ nfs_mounts }}"
  when:
    - not (nfs_server | bool)
    - nfs_mounts is defined
    - nfs_mounts | length != 0