---
- name: install dependence packages
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - zlib
    - zlib-devel
    - openssl
    - openssl-devel

- name: check ruby is installed or not
  shell:
    which ruby
  ignore_errors: true
  register: ruby_state

- name: check ruby version
  shell: ruby -v
  ignore_errors: true
  register: ruby_version
  when:
    - ansible_os_family | lower == 'redhat'
    - ruby_state is success

- name: download ruby
  get_url:
    url: "{{ ruby_download_url }}"
    dest: /tmp/
  ignore_errors: true
  when:
    - ansible_os_family | lower == 'redhat'
    - ruby_state is failed or ruby_version.stdout.split()[1] <= '2.2'

- name: unarchive ruby to destination
  unarchive:
    remote_src: true
    src: /tmp/ruby-2.6.3.tar.gz
    dest: /tmp
  ignore_errors: true
  when:
    - ansible_os_family | lower == 'redhat'
    - ruby_state is failed or ruby_version.stdout.split()[1] <= '2.2'

- name: install ruby
  shell:
    cd /tmp/ruby-2.6.3 && ./configure && make && make install
  ignore_errors: true
  when:
    - ansible_os_family | lower == 'redhat'
    - ruby_state is failed or ruby_version.stdout.split()[1] <= '2.2'