- name: restart systemd-modules-load
  service:
    name: systemd-modules-load
    enabled: yes
    state: restarted

- name: restart ipvsadm
  service:
    name: ipvsadm
    enabled: yes
    state: restarted