- name: check flannel config directory
  file:
    path: /etc/flannel
    owner: root
    group: root
    mode: 0755
    state: directory

- name: check flannel certs directory
  copy:
    src: certs/
    dest: "{{ flannel_tls_dir | default('/etc/flannel/certs') }}"
    owner: root
    group: root
    mode: 0644
  when:
    - etcd_tls | bool

- name: copy flannel service file
  copy:
    src: flanneld.service
    dest: /usr/lib/systemd/system/flanneld.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart flanneld

- name: render flannel config
  template:
    src: flanneld.conf.j2
    dest: /etc/flannel/flanneld.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart flanneld
