---
- name: disable ssh password authentication
  tags: system-init-sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: PasswordAuthentication no
    state: present
  when:
    - disable_password_authentication | bool
  notify:
    - restart sshd

- name: enable ssh password authentication
  tags: system-init-sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: PasswordAuthentication yes
    state: present
  when:
    - not (disable_password_authentication | bool)
  notify:
    - restart sshd

- name: disable dns resolve for sshd
  tags: system-init-sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
    insertafter: "^#UseDNS"
    state: present
  notify:
    - restart sshd

- name: config limits
  tags: system-init-limits
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
    state: present
  with_items: "{{ limits }}"

- name: set timezone
  tags: system-init-timezone
  timezone:
    name: "{{ tzname }}"
  notify:
    - restart crond

- name: disable services for redhat family
  tags: system-init-service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  with_items: "{{ disable_services }}"

- name: disable services for redhat family 6
  tags: system-init-service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  with_items: "{{ disable_services_rhel6 }}"
  when:
    - ansible_facts.distribution_major_version == '6'

- name: disable services for redhat family 7
  tags: system-init-service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items: "{{ disable_services_rhel7 }}"
  when:
    - ansible_facts.distribution_major_version == '7'

- name: disable selinux
  tags: system-init-selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: "^SELINUX="
    line: SELINUX=disabled

- name: disable swap
  tags: system-init-swap
  lineinfile:
    path: /etc/fstab
    regexp: "^([^#]*swap.*)"
    line: '#\1'
    backrefs: yes
  when:
    - disable_swap | bool

- name: yum repos config
  tags: system-init-repo
  block:
    - name: copy yum repos for rhel 6 (not aliyun ecs)
      copy:
        dest: "/etc/yum.repos.d/{{ item.split('_')[0] }}.repo"
        src: "{{ item }}"
        owner: root
        group: root
        mode: "0644"
      with_items:
        - epel_6.repo
        - CentOS-Base_6.repo
      when:
        - ansible_facts.distribution_major_version == '6'
        - "'alibaba' not in ansible_facts.product_name.lower()"

    - name: copy yum repos for rhel 7 (not aliyun ecs)
      copy:
        dest: "/etc/yum.repos.d/{{ item.split('_')[0] }}.repo"
        src: "{{ item }}"
        owner: root
        group: root
        mode: "0644"
      with_items:
        - epel_7.repo
        - CentOS-Base_7.repo
      when:
        - ansible_facts.distribution_major_version == '7'
  when:
    - ansible_facts.distribution.lower() == 'centos'
    - "'alibaba' not in ansible_facts.product_name.lower()"

- name: install packages
  tags: system-init-package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: set vim
  tags: system-init-vim
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: configure kernel parameters at runtime(sysctl)
  tags: system-init-sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ sysctl_config }}"

- name: config python pip source
  tags: system-init-pip
  block:
    - name: check pip is set or not
      stat:
        path: /etc/pip.conf
      register: pip_stat

    - name: copy pip config to /etc/pip.conf
      copy:
        src: pip.conf
        dest: /etc/pip.conf
        owner: root
        group: root
        mode: "0644"
      when:
        - not pip_stat.stat.exists

- name: create ansible facts directory
  tags: system-init-ansible-facts
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: "0755"
