---
- name: restart php74-php-fpm
  tags: php74-service, php74-service-reload, php74-service-start
  service:
    name: php74-php-fpm
    state: restarted
    enabled: yes
  when:
    - start_php74_service is defined
    - start_php74_service | bool
