- name: copy kube-scheduler binary file
  copy:
    src: "{{ kube_scheduler_binary }}"
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755
  when:
    - kube_scheduler_binary | mandatory
    - kube_scheduler_binary != ""
