---
- name: stopped chronyd
  service: 
    name: chronyd
    state: stopped
    enabled: no
  when:
    - ansible_os_family | lower == 'redhat'
    - ansible_distribution_major_version == '7'

- name: restarted ntpd
  service: 
    name: ntpd
    state: restarted
    enabled: yes
