---
- name: install chrony package
  package:
    name: chrony
    state: present

- name: render chrony config (/etc/chrony.conf)
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart chronyd

- name: get all services
  service_facts:

- name: stop ntpd if ntpd is running or installed
  service:
    name: ntpd
    state: stopped
    enabled: false
  when: "'ntpd' in services"
