---
- name: manage authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: "{{ item.state | default('present', boolean=true) }}"
    key: "{{ item.key }}"
    key_options: "{{ item.key_options | default(omit)}}"
  with_items: "{{ users }}"
