---
- name: install dhcp
  package:
    name: dhcp
    state: present

- name: copy dhcpd config file to dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart dhcpd

