---
- name: restart cobblerd
  service:
    name: cobblerd
    enabled: yes
    state: restarted

- name: restart httpd
  service:
    name: httpd
    enabled: yes
    state: restarted

- name: restart tftp
  service:
    name: tftp
    enabled: yes
    state: restarted

- name: restart rsyncd
  service:
    name: rsyncd
    enabled: yes
    state: restarted

- name: cobbler sync
  shell:
    cobbler sync