---
- hosts: "{{ host }}"
  gather_facts: "{{ gather_facts | default('no') }}"
  tasks:
    - name: check salt minion installed or not
      ansible.windows.win_stat:
        path: C:\salt
      register: win_salt
    
    - name: install windows salt minion
      ansible.windows.win_package:
        state: present
        path: "{{ url | default('https://repo.saltstack.com/windows/Salt-Minion-3003-Py3-AMD64-Setup.exe') }}"
        arguments:
          - /minion-name={{ host }}
          - /master={{ master }}
          - /start-minion=1
          - /S
      when: not win_salt.stat.exists or not win_salt.stat.isdir
