---
- hosts: "{{ h }}"
  gather_facts: "{{ gather_facts | default('no') }}"
  tasks:
    - name: install windows package management tool chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: install or uninstall windows packages with chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: "{{ state | default('present') }}"
        version: "{{ version | default(omit) }}"
      with_items: "{{ pkgs.split(',') | list }}"
