---
- name: manage authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: "{{ item.state | default('present', boolean=true) }}"
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ users }}"