---
- name: add authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ users }}"
  when:
    - item.state == "present"

- name: delete authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: absent
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ users }}"
  when:
    - item.state == "absent"