---
- name: started php72-php-fpm
  tags: php72-service-started
  service:
    name: php72-php-fpm
    state: started
    enabled: yes
  when:
    - start_php72_service is defined
    - start_php72_service | bool

- name: stopped and disable php72-php-fpm
  tags: php72-service-stopped
  service:
    name: php72-php-fpm
    state: stopped
    enabled: no
  when:
    - start_php72_service is defined
    - not (start_php72_service | bool)
