---
- name: copy openresty repo
  copy:
    src: openresty.repo
    dest: /etc/yum.repos.d/openresty.repo
    owner: root
    group: root
    mode: 0644

- name: install openresty
  package:
    name: openresty
    state: present

- name: create group to run openresty
  group:
    name: "{{ openresty_group }}"
    state: present
    system: yes

- name: create user to run openresty
  user:
    name: "{{ openresty_user }}"
    state: present
    shell: /sbin/nologin
    create_home: no
    system: yes
    group: "{{ openresty_group }}"

- name: change owner for openresty temp
  file:
    path: "{{ item }}" 
    state: directory
    owner: "{{ openresty_user }}"
    group: root
    mode: 0700
    recurse: yes
  with_items:
    - "/usr/local/openresty/nginx/client_body_temp"
    - "/usr/local/openresty/nginx/fastcgi_temp"
    - "/usr/local/openresty/nginx/proxy_temp"
    - "/usr/local/openresty/nginx/scgi_temp"
    - "/usr/local/openresty/nginx/uwsgi_temp"

- name: create openresty extra config directory
  file:
    path: /usr/local/openresty/nginx/conf/conf.d
    state: directory 
    owner: root
    group: root
    mode: 0755

- name: create openresty log directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ openresty_log_dir }}"

- name: create openresty certs directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ openresty_certs_dir }}"

- name: copy nginx certs
  copy:
    src: certs
    dest: "{{ openresty_certs_dir }}"
    owner: root
    group: root
    mode: 0755
  notify:
    - reload openresty

- name: copy nginx extra config
  copy:
    src: conf.d
    dest: "{{ openresty_extra_config_dir }}"
    owner: root
    group: root
    mode: 0755
  notify:
    - reload openresty

- name: render nginx config
  template:
    src: nginx.conf.j2
    dest: /usr/local/openresty/nginx/conf/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload openresty

- name: copy openresty start script
  template:
    src: openresty.sh.j2
    dest: /etc/init.d/openresty
    owner: root
    group: root
    mode: 0755
  notify:
    - reload openresty
