---
- name: install capistrano packages
  gem:
    name: "{{ item }}"
    state: present
    user_install: no
    repository: https://mirrors.aliyun.com/rubygems/
  with_items:
    - capistrano
    - capistrano-scm-copy
    - net-ssh
    - bcrypt_pbkdf
    - ed25519