---
- name: install dependence packages
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - zlib
    - zlib-devel
    - openssl
    - openssl-devel

- name: check ruby is installed or not
  shell: |
    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin && which ruby
  ignore_errors: true
  register: ruby_state

- name: check ruby version
  shell: |
    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin && ruby -v
  ignore_errors: true
  register: ruby_version
  when:
    - ansible_facts.os_family.lower() == 'redhat'
    - ruby_state is success

- name: download ruby
  get_url:
    url: "{{ ruby_download_url }}"
    dest: /tmp/
  ignore_errors: true
  when:
    - ansible_facts.os_family.lower() == 'redhat'
    - ruby_state is failed or ruby_version.stdout.split()[1] <= '2.2'

- name: unarchive ruby to destination
  unarchive:
    remote_src: true
    src: /tmp/ruby-2.6.3.tar.gz
    dest: /tmp
  ignore_errors: true
  when:
    - ansible_facts.os_family.lower() == 'redhat'
    - ruby_state is failed or ruby_version.stdout.split()[1] <= '2.2'

- name: install ruby
  shell:
    cd /tmp/ruby-2.6.3 && ./configure && make && make install
  ignore_errors: true
  when:
    - ansible_facts.os_family.lower() == 'redhat'
    - ruby_state is failed or ruby_version.stdout.split()[1] <= '2.2'

- name: link ruby and gem
  file:
    path: "/usr/bin/{{ item }}"
    src: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - ruby
    - gem
